spring.application.name=RAGP01
#spring.ai.google.genai.api-key=${GEMINI_API_KEY}
#spring.ai.google.genai.chat.options.model=${GEMINI_MODEL:gemini-2.5-flash-lite}

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=rag_ai_p01
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.use-tls=false


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.model=mxbai-embed-large
spring.ai.ollama.chat.model=llama3